### ISSUE TITLE
BleGattcWriteExecute function not recognized by xcompile

### ISSUE THREAD

**Issue by dcambron** [LairdCP/BL654-Applications#1]
Using the 29.4.6.0 firmware with the 29.4.6.0 compiler on BL654, I am trying to add long write functionality to the AT command set. But the Xcompiler does not recognize the token for the BleGattcWriteExecute function. I cannot find any examples that use this function so I wonder is it actually implemented in the Laird SmartBasic engine?

Error during XCompile (Tokenise line error):
rc=BleGattcWriteExecute(hConn,nArg[2])

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compile Error: (0x0433) TOK_UNEXPECTED_TOKEN_IN_EXPR
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

File : $LIB$.AT.interface.sb
Line : 3162
Source : rc=BleGattcWriteExecute(hConn,nArg[2])
: -------^

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mtwooburn** [comment]
Best Regards,

Mahendra Tailor
Technology Leader
Laird Connectivity
www.lairdconnect.com<http://www.lairdconnect.com/>

**Comment by mtwooburn** [comment]
And my apologies that the user guide is wrong and have updated that.


Best Regards,

Mahendra Tailor
Technology Leader
Laird Connectivity
www.lairdconnect.com<http://www.lairdconnect.com/>

**Comment by dcambron** [comment]
THANK YOU!!!
