### ISSUE TITLE
Using "AT+GCTM" command can not found characteristics in my BM70 microchip

### ISSUE THREAD

**Issue by HungLearner** [LairdCP/BL654-Applications#2]
Hi, I'm already compiler "AT Interface" in my BL654 usb dongle and do something.
But when i use "AT+GCTM", my output doesn't show any BM70 UUID.

![image](https://user-images.githubusercontent.com/37573331/119370168-9187de80-bce7-11eb-8fff-3f605e818d34.png)

```
AT+GCTM 1

TM:S:1 ,(5) ,FE011800
TM: C:3 ,00000002 ,FE012A00 ,0
TM: C:5 ,00000002 ,FE012A01 ,0

TM:S:16 ,(32) ,FE01180A
TM: C:18 ,00000002 ,FE012A29 ,0
TM: C:20 ,00000002 ,FE012A24 ,0
TM: C:22 ,00000002 ,FE012A25 ,0

TM: C:24 ,00000002 ,FE012A27 ,0
TM: C:26 ,00000002 ,FE012A26 ,0
TM: C:28 ,00000002 ,FE012A28 ,0

TM: C:30 ,00000002 ,FE012A23 ,0
TM: C:32 ,00000002 ,FE012A2A ,0

TM:S:48 ,(51) ,FC035343
TM: C:50 ,00000018 ,FB045343 ,0
TM:  D:51 ,FE012902

TM:S:64 ,(67) ,FA055343
TM: C:66 ,00000018 ,F9065343 ,0
TM:  D:67 ,FE012902

TM:S:80 ,(88) ,F8075343
TM: C:82 ,0000001C ,F7085343 ,0
TM:  D:83 ,FE012902

TM: C:85 ,0000000C ,F6095343 ,0
TM: C:87 ,00000018 ,F50A5343 ,0

TM:  D:88 ,FE012902
TM:  D:65535 ,FE01FFFF
TM:  D:65535 ,FE01FFFF
TM:  D:65535 ,FE01FFFF
TM:  D:65535 ,FE01FFFF
```

**Comment by thedjnK** [comment]
The handles used by smartBASIC are using the compressed Nordic SDK form, the last 4 hex digits of a handle match the last 4 hex digits of the first set in a UUID. The UART UUID starts with "4953**5343**-x" and the output shows "TM:S:48 ,(51) ,FC03**5343**" therefore it is listed

**Comment by HungLearner** [comment]
> The handles used by smartBASIC are using the compressed Nordic SDK form, the last 4 hex digits of a handle match the last 4 hex digits of the first set in a UUID. The UART UUID starts with "4953**5343**-x" and the output shows "TM:S:48 ,(51) ,FC03**5343**" therefore it is listed

But I don't know where is "49535343-1E4D-4BD9-BA61-23C647249616", and how can I use it to send hexstring?

**Comment by HungLearner** [comment]
I think my problem is solved.
