### ISSUE TITLE
How to create more connection in BL654?

### ISSUE THREAD

**Issue by HungLearner** [LairdCP/BL654-Applications#4]
In this product spec, I found it support "Up to 8 BLE connections".
But I got "ERROR 80" in second device connection.

![image](https://user-images.githubusercontent.com/37573331/119443736-ad799780-bd5c-11eb-9b0e-c8035e4ed4bc.png)

![image](https://user-images.githubusercontent.com/37573331/119443941-02b5a900-bd5d-11eb-9e52-fd42e631b11f.png)

**Comment by tylermodelski11** [comment]
Was there any resolution on this issue? I am experiencing the same thing.

**Comment by HungLearner** [comment]
> Was there any resolution on this issue? I am experiencing the same thing.

Hi, I'm solved this problem.

First, you can reference "BL65x AT Interface application" documents and call "ATS" command to apply it.
For example: ATS 126=2  <-(two connection)
**Remark: Remember call AT&W command to store the parameter.**

![image](https://user-images.githubusercontent.com/37573331/144538884-8e553fc0-dd7f-427b-9717-e70035f10dcd.png)

![image](https://user-images.githubusercontent.com/37573331/144538905-54e768cc-406e-4941-81bc-7f9d5a6cc050.png)

**Comment by tvbarnette999** [comment]
I was running into the same problem, despite having set S-reg 126 > 1. What solved it for me was making sure startup-flags (S100) bit 3 was cleared. When that bit is set, [this if block](https://github.com/LairdCP/BL654-Applications/blob/ffd769b0a703bb44f2e8a2c8ea5866b8bfd362f3/ATinterface/%24LIB%24.AT.interface.sb#L4876) sets it to 1 regardless of S126 or the value of bit 0 of S100.

**Comment by RAH-Laird** [comment]
When attempting to make multiple connections while working with the AT Interface smartBASIC application, it is important to note this can only be done in non-vSP mode.  You must first ensure that the Max Bidirectional setting is disabled (bit 3 in ATS 100), as well as disabling the vSP service, which is on by default. Both of these are set in S Register 100 as tvbarnette999 pointed out. 
If Max Bidirectional throughput is enabled it will only allow one connection.
