### ISSUE TITLE
ATinterface: Connection to extended advert fails

### ISSUE THREAD

**Issue by Nema91** [LairdCP/BL654-Applications#9]
Establishing a connection with a peripheral, advertising extended connectable packets (ADV_EXT_IND, AUX_ADV_IND) on 1M PHY fails. 
![UwTerminalX_Scan_ConnectFailed_Modified](https://user-images.githubusercontent.com/115552063/195086890-e87c19a6-654f-4d60-92be-43db8b4722e5.png)

Fixed it with modifing "ConnSetup" function in "$LIB$.AT.interface.sb":

> //OK to start an outgoing connection	
	rc = BleConnectConfig(11, 1) // Set to extended connection, so connection to peripherals with extended advertising is activated
	#cmpif    0x00000003 : AssertRC(2830)
    if lngRange then
		rc = BleConnectConfig(10, 4) // Set PHY to perform connection on to CODED
		#cmpif    0x00000003 : AssertRC(2833)
        rc = BleConnectExtended(sArg$[ArgIDAddress], nArg[ArgIDConnectionTimeout], nArg[ArgIDMinConnInterval], nArg[ArgIDMaxConnInterval], nArg[ArgIDLinkSupervisionTimeout], lngRange, EXTADV_FILTER_NONE)
        #cmpif 0x00000004 : DbgMsg("Called BleConnectExtended()")
    else	
		rc = BleConnectConfig(10, 1) // Set PHY to perform connection on to 1MPHY
		#cmpif    0x00000003 : AssertRC(2838)
        rc = BleConnect(sArg$[ArgIDAddress], nArg[ArgIDConnectionTimeout], nArg[ArgIDMinConnInterval], nArg[ArgIDMaxConnInterval], nArg[ArgIDLinkSupervisionTimeout])
    endif

**Comment by eriklins** [comment]
Hello Nema91,
thanks for raising this issue here. It has been resolved in the latest version pushed here. Would be great we could get some feedback from you before closing off this issue here.
Thanks and best regards,
ER!K

**Comment by Nema91** [comment]
Hello ER!K,

thanks for your support. It works fine so far!
I was unsure if it will work because I couldn't see the call of "BleConnectConfig" in the code comparison view.
Is this function called in "BleConnectExtended"?

Best regards,
Christian

**Comment by eriklins** [comment]
Hi Christan,
BleConnectExtended() can be considered a successor function to BleConnect() and can handle both legacy and extended adverts without the need to prior call BleConnectConfig().
Best regards,
ER!K
